language: node_js
sudo: true
dist: trusty
node_js:
- '6'
before_install:
- sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
- sudo apt-get install -qq -y gcc-arm-none-eabi --force-yes
- wget -O arduino.tgz https://downloads.arduino.cc/arduino-1.8.1-linux64.tar.xz
- tar -xf arduino.tgz
- sudo apt-get install pkg-config cmake openssl libc-ares-dev
- wget http://mosquitto.org/files/source/mosquitto-1.3.1.tar.gz
- tar xzf mosquitto-1.3.1.tar.gz
- cd mosquitto-1.3.1
- cmake .
- sudo make install
- cd -
before_script:
- mosquitto -d
- export PATH=`pwd`/arduino-1.8.1/:$PATH
after_script:
- killall mosquitto
deploy:
-
  provider: npm
  email: jononor@gmail.com
  api_key:
    secure: d/v+q0HL0Lwtbywm5t632ME0YJ6EN2N/6E4FeiVY/oFULMO9C07lZV7xYc5Cd2GmAwKpH1byjGZa8AFQ2OmajTGDXdBZQsz2W87C/F1qYsxjxk/rXqVBzXlS4AaWkx969JCiabnaw0+O9LUo+bLqKra6dogDMSgf5qEKl0RES4o=
  on:
    tags: true
    repo: microflo/microflo
